/**
 * UCSharpLogs.h
 * This file defines the logging categories for the UCSharp plugin.
 * It is used to categorize and filter log messages generated by the plugin.
 *
 */

#pragma once
#include "CoreMinimal.h"
#include "Logging/LogMacros.h"

DECLARE_LOG_CATEGORY_EXTERN(LogUCSharp, Log, All);
