using EpicGames.Core;
using EpicGames.UHT.Types;
using EpicGames.UHT.Tables;
using EpicGames.UHT.Utils;
using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace UCSharp
{
[UnrealHeaderTool]
static class UCSharpExporter
{
	// 插件根目录
	public static string PluginDirectory = "";
	// Managed工程目录
	public static string ManagedDirectory = "";
	public static string ManagedGeneratedDir = "";
	public static string NativeGeneratedDir = "";

	public static IUhtExportFactory Factory { get; private set; } = null!;
	public static UhtSession Session => Factory.Session;

	/**
	 * 初始化生成器环境
	 */
	private static void Initialize(IUhtExportFactory factory)
	{
		Factory = factory;
		UHTManifest.Module PluginModule = factory.PluginModule!;

		// 获取UCSharp插件根目录
		// BaseDirectory -- E:\\H73\\ucsharp\\Plugins\\UCSharp\\Source\\UCSharp"
		PluginDirectory = Path.GetDirectoryName(Path.GetDirectoryName(PluginModule.BaseDirectory))!;
		ManagedDirectory = Path.Combine(PluginDirectory, "Managed");
		ManagedGeneratedDir = Path.Combine(ManagedDirectory, "Generated");
		NativeGeneratedDir = Path.Combine(PluginDirectory, "Source", "UCSharp", "Generated");
		Directory.CreateDirectory(ManagedGeneratedDir);
		Directory.CreateDirectory(NativeGeneratedDir);
	}

	[UhtExporter(Name = "UCSharpExporter", ModuleName = "UCSharp", Options = UhtExporterOptions.Default)]
	private static void Generate(IUhtExportFactory factory)
	{
		factory.Session.LogInfo("Start UCSharpExporter!");
		factory.Session.LogInfo("---------------------------------");
		// 初始化
		Initialize(factory);

		var cppBuilder = new StringBuilder();
        cppBuilder.AppendLine("#include \"UCSharpRuntime.h\"");
        cppBuilder.AppendLine("#include \"UObject/GeneratedCppIncludes.h\"");
        cppBuilder.AppendLine();
        cppBuilder.AppendLine("namespace UCSharpGenerated");
        cppBuilder.AppendLine("{");
        cppBuilder.AppendLine("\tvoid RegisterPropertyMetadata()");
        cppBuilder.AppendLine("\t{");

		List<UhtClass> classes = new();
		List<Task?> tasks = new();
		foreach (UhtModule module in Session.Modules)
		{
			if (module.Module.ModuleType != UHTModuleType.EngineRuntime && module.Module.ModuleType != UHTModuleType.GameRuntime)
			{
				continue;
			}

			QueueClassExports(module.ScriptPackage, module.ScriptPackage, classes, tasks);
		}

		// Wait for all the classes to export
		Task[]? waitTasks = tasks.Where(x => x != null).Cast<Task>().ToArray();
		if (waitTasks.Length > 0)
		{
			Task.WaitAll(waitTasks);
		}

		cppBuilder.AppendLine("\t}");
        cppBuilder.AppendLine();
        cppBuilder.AppendLine("\tvoid UnregisterPropertyMetadata()");
        cppBuilder.AppendLine("\t{");
        cppBuilder.AppendLine("\t\tFUCSharpPropertyRegistry::Get().Reset();");
        cppBuilder.AppendLine("\t}");
        cppBuilder.AppendLine("}");

        File.WriteAllText(Path.Combine(NativeGeneratedDir, "UCSharpGeneratedProperties.gen.cpp"), cppBuilder.ToString(), new UTF8Encoding(false));


		// Finish the export process
		// TODO:

		factory.Session.LogInfo("UCSharpExporter finished.");
	}

	private static void QueueClassExports(UhtPackage package, UhtType type, List<UhtClass> classes, List<Task?> tasks)
	{
		if (type is UhtClass classObj)
		{
			if (CanExportClass(classObj))
			{
				classes.Add(classObj);
				tasks.Add(Factory.CreateTask((factory) => { ExportClass(classObj); }));
			}
		}
		foreach (UhtType child in type.Children)
		{
			QueueClassExports(package, child, classes, tasks);
		}
	}

	private static bool CanExportClass(UhtClass classObj)
	{
		if (!classObj.ClassFlags.HasAnyFlags(EClassFlags.RequiredAPI | EClassFlags.MinimalAPI))
		{
			return false;
		}

		if (classObj.ClassFlags.HasAnyFlags(EClassFlags.Abstract))
		{
			return false;
		}

		// Test only actor classes
		return classObj.IsActorClass;
	}

	private static void ExportClass(UhtClass classObj)
	{
		using BorrowStringBuilder borrower = new(StringBuilderCache.Big);
		ExportClass(borrower.StringBuilder, classObj);
		// string fileName = Factory.MakePath(classObj.EngineName, ".script.h");
        var fileName = Path.Combine(ManagedGeneratedDir, $"{classObj.EngineName}.gen.cs");
		Factory.CommitOutput(fileName, borrower.StringBuilder);
	}

	static void ExportClass(StringBuilder sb, UhtClass classObj)
	{
		var className = classObj.EngineName; // e.g. ATestActor
        var namespaceName = "UCSharp.Generated.Actors";
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("using UCSharp.Core;");
        sb.AppendLine("using UCSharp.Generated;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"\tpublic sealed partial class {className} : GeneratedActorBase");
        sb.AppendLine("\t{");
        sb.AppendLine($"\t\tpublic {className}(IntPtr handle) : base(handle) {{ }}");
        sb.AppendLine();

        foreach (var property in classObj.Properties.OfType<UhtProperty>())
        {
            if (!ShouldExportProperty(property))
            {
                continue;
            }

            var (Getter, Setter) = MapPropertyType(property, out var csType);
			if (csType == null)
			{
				continue;
			}

            var propertyId = ComputePropertyId(classObj.EngineName, property.SourceName);
            var csPropertyName = property.SourceName;

            sb.AppendLine($"\t\tprivate const uint PropertyId_{csPropertyName} = 0x{propertyId:X8};");
            sb.AppendLine($"\t\tpublic {csType} {csPropertyName}");
            sb.AppendLine("\t\t{");
            sb.AppendLine($"\t\t\tget => {Getter}(PropertyId_{csPropertyName});");
            sb.AppendLine($"\t\t\tset => {Setter}(PropertyId_{csPropertyName}, value);");
            sb.AppendLine("\t\t}");
            sb.AppendLine();

            // cppBuilder.AppendLine($"\t\tFUCSharpPropertyRegistry::Get().RegisterProperty(0x{propertyId:X8}, {actor.EngineName}::StaticClass(), TEXT(\"{property.SourceName}\"));");
        }

        sb.AppendLine("\t}");
        sb.AppendLine("}");
    }

	private static bool ShouldExportProperty(UhtProperty property)
    {
		// 或许应该全部导出
		return property.PropertyFlags.HasAnyFlags(EPropertyFlags.BlueprintVisible | EPropertyFlags.Edit);
	}

	private static (string Getter, string Setter) MapPropertyType(UhtProperty property, out string? csType)
    {
		if (property is UhtIntProperty)
		{
			csType = "int";
			return ("Native.GetIntFast", "Native.SetIntFast");
		}

		if (property is UhtFloatProperty)
		{
			csType = "float";
			return ("Native.GetFloatFast", "Native.SetFloatFast");
		}

		if (property is UhtBoolProperty)
		{
			csType = "bool";
			return ("Native.GetBoolFast", "Native.SetBoolFast");
		}

		if (property is UhtStrProperty)
		{
			csType = "string";
			return ("Native.GetString", "Native.SetStringFast");
		}

		if (property is UhtObjectProperty)
		{
			csType = "IntPtr";
			return ("Native.GetObjectFast", "Native.SetObjectFast");
		}

		csType = null;
		return default;
    }

    private static uint ComputePropertyId(string className, string propertyName)
    {
        uint hash = 2166136261u;
        foreach (char c in className)
        {
            hash ^= c;
            hash *= 16777619u;
        }
        foreach (char c in propertyName)
        {
            hash ^= c;
            hash *= 16777619u;
        }
        return hash;
    }
} // End class UCSharpExporter

} // End namespace